CREATE TABLE Products(
	product_id INT AUTO_INCREMENT PRIMARY KEY,
	product_name VARCHAR(50),
    product_category VARCHAR(50) NOT NULL,
    price_per_kg DECIMAL(8,2),
    available BOOLEAN,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);